# Importando a Base

In [11]:
import pandas as pd

tabela = pd.read_csv('exportacao_Afghanistan.csv')

display(tabela)

,Year,Month,Country,City,SH4 Code,SH4 Description,SH2 Code,SH2 Description,Economic Block,US$ FOB,Net Weight
0,2014,1,Afghanistan,Cubatão - SP,207,"Meat and edible offal, of the poultry of headi...",2,Meat and edible meat offal,Asia (minus MIDDLE EAST),30606,21458
1,2014,1,Afghanistan,Itajaí - SC,207,"Meat and edible offal, of the poultry of headi...",2,Meat and edible meat offal,Asia (minus MIDDLE EAST),226279,155697
2,2014,1,Afghanistan,Montenegro - RS,207,"Meat and edible offal, of the poultry of headi...",2,Meat and edible meat offal,Asia (minus MIDDLE EAST),243053,183724
3,2014,1,Afghanistan,Paranaguá - PR,207,"Meat and edible offal, of the poultry of headi...",2,Meat and edible meat offal,Asia (minus MIDDLE EAST),338113,232985
4,2014,1,Afghanistan,Rio Grande - RS,207,"Meat and edible offal, of the poultry of headi...",2,Meat and edible meat offal,Asia (minus MIDDLE EAST),196860,132996
...,...,...,...,...,...,...,...,...,...,...,...
725,2020,12,Afghanistan,Pompéia - SP,7318,"Screws, bolts, nuts, coach screws, screw hooks...",73,Articles of iron or steel,Asia (minus MIDDLE EAST),72,3
726,2020,12,Afghanistan,Pompéia - SP,7326,Other articles of iron or steel,73,Articles of iron or steel,Asia (minus MIDDLE EAST),20,0
727,2020,12,Afghanistan,Pompéia - SP,8421,"Centrifuges, including centrifugal dryers; fil...",84,"Nuclear reactors, boilers, machinery and mecha...",Asia (minus MIDDLE EAST),37,0
728,2020,12,Afghanistan,Pompéia - SP,8424,Mechanical appliances (whether or not hand-ope...,84,"Nuclear reactors, boilers, machinery and mecha...",Asia (minus MIDDLE EAST),53052,7364
729,2020,12,Afghanistan,Pompéia - SP,8481,"Taps, cocks, valves and similar appliances for...",84,"Nuclear reactors, boilers, machinery and mecha...",Asia (minus MIDDLE EAST),551,23

# Informações Gerais

In [14]:
tabela.info
display(tabela.describe())

,Year,Month,SH4 Code,SH2 Code,US$ FOB,Net Weight
count,730.000000,730.000000,730.000000,730.000000,7.300000e+02,7.300000e+02
mean,2017.352055,6.728767,2022.982192,20.139726,1.690023e+05,2.104314e+05
std,2.040913,3.301971,2665.584205,26.583041,3.356255e+05,8.457382e+05
min,2014.000000,1.000000,202.000000,2.000000,1.000000e+00,0.000000e+00
25%,2016.000000,4.000000,207.000000,2.000000,1.038900e+04,3.655000e+03
50%,2018.000000,6.000000,504.000000,5.000000,4.233700e+04,2.618350e+04
75%,2019.000000,10.000000,2516.000000,25.000000,1.582802e+05,1.166645e+05
max,2020.000000,12.000000,9617.000000,96.000000,3.143211e+06,1.285000e+07

# Como foi a evolução das exportações para a Afgnistão ao longo dos anos?

In [27]:
tabela_ano = tabela.groupby('Year').sum()
tabela_ano = tabela_ano[['US$ FOB']]
def formartar(valor):
    return f"${valor:,.2f}"

tabela_ano["US$ FOB"] = tabela_ano["US$ FOB"].map(formatar)
display(tabela_ano)

             US$ FOB
Year
2014  $11,721,368.00
2015   $6,706,901.00
2016   $8,782,814.00
2017   $9,276,428.00
2018  $16,994,642.00
2019  $32,459,656.00
2020  $37,429,851.00

# Quais os produtos mais exportados ao longo de todo o período?

,Year,Month,SH4 Code,SH2 Code,US$ FOB,Net Weight
SH4 Description,,,,,,
"Air or vacuum pumps, air or other gas compressors and fans; ventilating or recycling hoods incorporating a fan, whether or not fitted with filters",4035,11,16828,168,1304,94
"Animal (not fish) guts, bladders, stomachs and parts",20192,88,5040,50,59724,57880
"Apparatus based on the use of X-rays or of alpha, beta or gamma radiations, whether or not for medical, surgical, dental or veterinary uses, including radiography or radiotherapy apparatus, X-ray tubes and other X-ray generators, high tension generators,",2020,11,9022,90,104000,3640
"Articles for the conveyance or packing of goods, of plastics; stoppers, lids, caps and other closures, of plastics",2016,5,3923,39,43500,7050
Automatic regulating or controlling instruments and apparatus,2014,5,9032,90,30,0
...,...,...,...,...,...,...
"Tubes, pipes and hoses, of vulcanised rubber other than hard rubber, with or without their fittings (for example, joints, elbows, flanges)",6050,26,12027,120,354,8
"Uncoated paper and paperboard, of a kind used for writing, printing or other graphic purposes, and non-perforated punch-cards and punch tape paper, in rolls or rectangular (including square) sheets, of any size, other than paper of heading No 4801 or 4803",2017,1,4802,48,184347,302208
"Vegetable materials and vegetable waste, vegetable residues and by-products, whether or not in the form of pellets, of a kind used in animal feeding",2018,10,2308,23,19344,24180
Wire of iron or non-alloy steel,2014,5,7217,72,2,0
Wire of stainless steel,2018,11,7223,72,1687,572